mfvidz/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('movies', views.movies, name='movies'),
    path('index', views.index, name='index'),
    path('detail', views.detail, name='detail'),

    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # Hall
    path('myfavvids/create', views.CreateList.as_view(), name='create_list'),
    path('myfavvids/<int:pk>', views.DetailHall.as_view(), name='detail_hall'),
    path('myfavvids/<int:pk>/update', views.UpdateList.as_view(), name='update_list'),
    path('myfavvids/<int:pk>/delete', views.DeleteList.as_view(), name='delete_list'),
    #video
    path('myfavvids/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),
    path('video//<int:pk>details', views.details, name='video_details'),

    #path('myfavvids/<int:pk>/adddetails', views.add_details, name='add_details'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/geo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('measurements.urls', namespace='measurements')),
]

zappy_project/zappy/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

halls/models.py
from django.db import models
from django.contrib.auth.models import User

class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

class Wiki(models.Model):
    title = models.CharField(max_length=255)
    pageid = models.IntegerField()
    wikitext = models.CharField(max_length=5000)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

halls/forms.py
from .models import Video
from django import forms

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url':'YouTube Url'}

class SearchForm(forms.Form):
   search_term = forms.CharField(max_length=255, label='Search for Videos:')

 #class wikiForm(forms.Form):
#    wiki_term = forms.CharField(max_length=255, label='Search for details:')

halls/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from .models import Hall, Video
from django.contrib.auth import authenticate, login
from .forms import VideoForm, SearchForm
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList
import urllib
import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

YOUTUBE_API_KEY = 'AIzaSyAJPcO-PsgVZuggw0EwMQr-K_SLPB5oas8'
TMDB_API_KEY = 'c170e51ce0b1532553de58afa5e61281'
base_url = 'https://api.themoviedb.org/3/'

def home(request):
    #recent_halls = Hall.objects.all().order_by('-id')[:3]
    #popular_halls = [Hall.objects.get(pk=1),Hall.objects.get(pk=2),Hall.objects.get(pk=3)]
    return render(request, 'halls/home.html')

def index(request):
	context = {}
	categories = ['now_playing', 'upcoming', 'popular', 'top_rated']

	try:
		for category in categories:
			endpoint = 'https://api.themoviedb.org/3/movie/{category}?api_key=c170e51ce0b1532553de58afa5e61281&language=en-US&page=1'
			url = endpoint.format(category=category, api_key=settings.TMDB_API_KEY)
			response = requests.get(url)
			context[category] = response.json()

	except:
		context['success'] = False
		context['message'] = 'Connection To TMDB API not available at the moment, Check Your Internet Connection and Try again later'


	return render(request, 'halls/index.html', context)

def detail(request):
	movie_detail = {}

	try:
		endpoint = 'https://api.themoviedb.org/3/movie/{movie_id}?api_key=c170e51ce0b1532553de58afa5e61281&language=en-US&append_to_response=videos'
		url = endpoint.format(movie_id=id, api_key=settings.TMDB_API_KEY)
		response = requests.get(url)
		movie_detail = response.json()
		movie_detail['success'] = True
	except:
		movie_detail['success'] = False
		movie_detail['message'] = 'Connection To TMDB API not available at the moment, Check Your Internet Connection and Try again later'

	return render(request, 'halls/details.html', {'movie_detail': movie_detail})


def search(request):
	result = {}
	if 'q' in request.GET:
		query = request.GET['q']

		try:
			endpoint = 'https://api.themoviedb.org/3/search/movie?api_key=c170e51ce0b1532553de58afa5e61281&query={query}'
			url = endpoint.format(api_key = settings.TMDB_API_KEY, query = query)
			response = requests.get(url)
			result = response.json()
			result['searched_item'] = query
			result['success'] = True
		except:
			result['searched_item'] = query
			result['message'] = 'Connection to TMDB API not Available at the moment try again later'
			result['success'] = False
	return render(request, 'halls/result.html', {'result': result})


def movies(request):
    url = f'{base_url}movie/upcoming?api_key={TMDB_API_KEY}&language=en-US&page=1'

    response = requests.get(url)
    movies = response.json()['results']
    context = {
        'title': 'Upcoming',
        'movies': movies,
    }
    return render(request, 'halls/movies.html', context)

@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user)
    return render(request, 'halls/dashboard.html', {'halls':halls})

#def wiki(request):
    #page = urllib.parse.parse_qs(parsed_url.query).get('page')
    #if 'video.title' in request.GET:
    #    username = request.GET['username']
    #    response = requests.get(f'https://en.wikipedia.org/w/api.php?action=parse&page={ video.title }&prop=wikitext&formatversion=2')
    #    user = response.json()

    #return render(request, 'halls/details.html', {
    #    'ip': geodata['ip'],
    #    'country': geodata['country_name'],
    #    'latitude': geodata['latitude'],
    #    'longitude': geodata['longitude'],
    ##    'api_key': 'AIzaSyC1UpCQp9zHokhNOBK07AvZTiO09icwD8I',  # Don't do this! This is just an example. Secure your keys properly.
    #    'is_cached': is_cached
    #})

def detail_search(request):
    wiki_form = wikiForm(request.GET)
    if wiki_form.is_valid():
        encoded_wiki_term = urllib.parse.quote(wiki_form.cleaned_data['wiki_term'])
        response = requests.get(f'https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch={ encoded_wiki_term }a&utf8=&format=json')
        return JsonResponse(response.json())
    return JsonResponse({'error':'Not able to validate form'})

def add_video(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    hall = Hall.objects.get(pk=pk)
    if not hall.user == request.user:
        raise Http404
    if request.method == 'POST':
            form = VideoForm(request.POST)
            if form.is_valid():
                video = Video()
                video.hall = hall
                video.url = form.cleaned_data['url']
                parsed_url = urllib.parse.urlparse(video.url)
                video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
                if video_id:
                    video.youtube_id = video_id[0]
                    response = requests.get(f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id[0] }&key={ YOUTUBE_API_KEY }')
                    json = response.json()
                    title = json['items'][0]['snippet']['title']
                    video.title = title
                    video.save()
                    return redirect('detail_hall', pk)
                else:
                    errors = form._errors.setdefault('url', ErrorList())
                    errors.append('Needs to be a YouTube URL')

    return render(request, 'halls/add_video.html', {'form':form, 'search_form':search_form})

@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        response = requests.get(f'https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={ encoded_search_term }&key={ YOUTUBE_API_KEY }')
        return JsonResponse(response.json())
    return JsonResponse({'error':'Not able to validate form'})

def details(request,id):
    response=requests.get(f'https://api.themoviedb.org/3/search/movie?api_key = { TMDB_API_KEY } &language=en-US&query={ encoded_search_term }&page=1&include_adult=false')
    data=response.json()
    return render(request,'detail.html',{"data":data})


class DeleteVideo(generic.DeleteView):
    model = Video
    template_name = 'halls/delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        return video

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class CreateList(generic.CreateView):
    model = Hall
    fields = ['title']
    template_name = 'halls/create_list.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateList, self).form_valid(form)
        return redirect('dashboard')

class UpdateList(LoginRequiredMixin,generic.UpdateView):
    model = Hall
    template_name = 'halls/update_list.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(UpdateList, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall

class DeleteList(LoginRequiredMixin,generic.DeleteView):
    model = Hall
    template_name = 'halls/delete_list.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall

class DetailHall(generic.DetailView):
    model = Hall
    template_name = 'halls/detail_hall.html'

halls/templates/halls/add_video.html
{% extends 'halls/base.html' %}
{% block content %}
<div class="container">
  <h2>Add Video to {{ hall.title }}</h2>
  <form method="post" id="submit_video">
  {% csrf_token %}
  {% load widget_tweaks %}


  {% for field in form %}
  <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
    {{ field.errors }}
    {{ field.label_tag }}
    {% render_field field class="form-control" %}
  </div>
  {% endfor %}


<button type="submit" class="btn btn-primary">Add</button>
</form>

<h2> OR </h2>
<form>
    {% for field in search_form %}
    <div class="form-group">
      {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}
</form>


<div id="search_results"></div>
<script>
  var delayTimer;
  $('#id_search_term').keyup(function() {
    clearTimeout(delayTimer);
    $('#search_results').text('Loading...');
    delayTimer = setTimeout(function() {
      var text = $('#id_search_term').val();
      $.ajax({
        url: '/video/search',
        data: {
          'search_term': text
        },
        dataType: 'json',
        success: function(data) {
          var results = '';
          $('#search_results').text('');
          results += '<div class="row">';
          data['items'].forEach(function(video) {
              results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
              results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] +
                '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
              results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
              results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Add</a></div></div></div>';
            });
             results += '</div>';
            $('#search_results').append(results);
        }
      });
    }, 1000);
  });
  function addVideo(video_id) {
    $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
    $('#submit_video').submit();
  }
</script>
</div>
{% endblock %}

halls/templates/halls/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>My Fav Vidz</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link href="{% static 'custom.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'popcorn.svg' %}" />
  <link href="#" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="#" />
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    {% load static %}
<img src="{% static 'favicon.svg' %}" alt="My image" width="100" height="100">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">My Fav Vidz</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
      <a class="p-2 text-dark" href="{% url 'movies' %}">Latest Upcoming movies</a>
      {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
      {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
    <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign up</a>
    {% endif %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  {% block content %}
  {% endblock %}

</body>

</html>

halls/templates/halls/create_list.html
{% extends 'halls/base.html' %}
{% block content %}
<div class="container">
<h2>Create Your Fav vidz list</h2>
<form method="post">
  {% csrf_token %}
  {% load widget_tweaks %}
  {% for field in form %}
  <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
    {{ field.errors }}
    {{ field.label_tag }}
    {% render_field field class="form-control" %}
  </div>
  {% endfor %}
<button type="submit" class="btn btn-primary">Create</button>
</form>
</div>
{% endblock %}

halls/templates/halls/dashboard.html
{% extends 'halls/base.html' %}
{% block content %}

<style>
.myDiv {
  border: 5px;
  background-color: lightblue;
  text-align: center;
  float: right;
}
</style>

<div class= "myDiv">
  <div class="feedgrabbr_widget" id="fgid_0145056a5516e10d51cbb87cb"></div>
<script>if (typeof (fg_widgets) === "undefined") fg_widgets = new Array(); fg_widgets.push("fgid_0145056a5516e10d51cbb87cb");</script>
<script async src="https://www.feedgrabbr.com/widget/fgwidget.js"></script>
</div>

<div class="container">

  <div class="text-center">
    <h1>{{ user.username }}'s favorite movie list</h1>
    <a href="{% url 'create_list' %}" class="btn btn-primary">Create New List</a>
  </div>

    {% for hall in halls %}

<h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
<a href="{% url 'delete_list' hall.id %}" class="btn btn-danger">Delete</a>
<a href="{% url 'update_list' hall.id %}" class="btn btn-primary">Edit</a>
<a href="{% url 'add_video' hall.id %}" class="btn btn-primary">Add Video</a>

    <div class="row">
      {% for video in hall.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
          <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="card-body">
            <p class="card-text">{{ video.title }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>

    {% endfor %}
</div>
{% endblock %}

halls/templates/halls/delete_list.html
{% extends 'halls/base.html' %}
{% block content %}
<div class="container">
<h2>Are you sure you want to delete this Hall of Fame?</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-danger">Delete</button>
</form>

<br>
<form method="post">

<h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>

</div>
{% endblock %}

halls/templates/halls/delete_video.html
{% extends 'halls/base.html' %}
{% block content %}
<div class="container">
  <h2>Are you sure you want to delete this video?</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>


  <div class="row">
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body">
          <p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}

halls/templates/halls/detail_hall.html
{% extends 'halls/base.html' %}
{% block content %}
<div class="container">
<h1>{{ hall.title }}</h1>
<h4 class="text-muted">{{ hall.user.username }}</h4>

{% if user.id == hall.user.id %}
<a href="{% url 'delete_list' hall.id %}" class="btn btn-danger">Delete</a>
<a href="{% url 'update_list' hall.id %}" class="btn btn-primary">Edit</a>
<a href="{% url 'add_video' hall.id %}" class="btn btn-primary">Add Video</a>
{% endif %}

    <div class="row">
      {% for video in hall.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
          <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="card-body">
            <p class="card-text">{{ video.title }}</p>
            {% if user.id == hall.user.id %}
            <a href="{% url 'delete_video' video.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'video_details' video.id %}" class="btn btn-primary">Details</a>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
      </div>

</div>
{% endblock %}

halls/templates/halls/details.html
{% extends 'halls/base.html' %}

{% load static %}

{% block content %}
	<div class="container">
		  <div class="row mt-3">
		    <div class="col-md-8">
				<p class="h3-responsive text-center bg-dark text-white">{{ movie_detail.original_title }} Trailer</p>

				<div class="row">
					<div class="embed-responsive embed-responsive-4by3">

					  {% for video in movie_detail.videos.results|slice:":1" %}
					  	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{video.key}}" allowfullscreen></iframe>
					  {% endfor %}

					</div>
				</div>
			</div>
			<div class="col-md-4">
				<p class="h3-responsive text-center bg-dark text-white">Poster Image</p>
				<div class="card mdb-color text-center z-depth-2">
					<div class="view">
						<img src="http://image.tmdb.org/t/p/w500//{{movie_detail.poster_path}}" class="img-fluid" alt="{{movie_detail.title}}">
					</div>
				</div>
			</div>
		</div>

		<p class="h3-responsive text-center bg-dark text-white mt-3">Description</p>


		<div class="row mt-3">
		    <div class="col-md-6">
				<div class="view">
					<img src="http://image.tmdb.org/t/p/w500//{{movie_detail.backdrop_path}}" class="img-fluid" alt="{{movie_detail.title}}">
				</div>
			</div>
			<div class="col-md-6">
				<p class="h3-responsive">Plot</p>
				<p>{{movie_detail.overview}}</p>
				<p class="h3-responsive"> Genre: </p>
				<p>
					{% for genre in movie_detail.genres %}
						{{genre.name}},
					{% endfor%}
				</p>
				<p><span class="h3-responsive">Release Date:</span> {{movie_detail.release_date}}</p>
				<p><span class="h3-responsive">Rating:</span> {{movie_detail.vote_average}}/10</p>
				<p><span class="h3-responsive">Tags:</span> {{movie_detail.tagline}}</p>
				<p class="h3-responsive">Production Companies</p>
				<p>
					{% for company in movie_detail.production_companies %}
						{{company.name}},
					{% endfor %}
				</p>
			</div>
		</div>
	</div>
{% endblock %}

halls/templates/halls/home.html
{% extends 'halls/base.html' %}
{% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">What's your personal list?</h1>
    <p class="lead text-muted">You what they are. They're your goto videos. You have a top 10 list and it's time to share them with the world. Click the button below to get started.</p>
    <p>
      <a href="{% url 'create_list' %}" class="btn btn-primary">Create Your List of Movies</a>
    </p>
  </div>
</section>


</div>
{% endblock %}

halls/templates/halls/index.html
{% extends 'halls/base.html' %}

{% block content %}

	{% if success == False %}
		<p>{{message}}</p>
	{% else %}

		<div class="container">
		  <div class="row mt-3">
		    <div class="col-md-8">
				<p class="h3-responsive text-center bg-dark text-white"> Now Showing in Cinemas</p>

				<div class="row">

					{% for movie in now_playing.results %}
						<div class="col-lg-4 col-md-12 mb-4">
						 <div class="card mdb-color text-center z-depth-2">
						 	<a href="{% url 'detail' id=movie.id %}">
						 	<div class="view overlay zoom">
							  <img src="http://image.tmdb.org/t/p/w500//{{ movie.poster_path }}" class="img-fluid" alt="{{ movie.title }}">
							</div>
							</a>
						  </div>
						</div>
					{% endfor %}

				</div>
		    </div>
		    <div class="col-md-4">
				<p class="h3-responsive text-center bg-dark text-white">Upcoming Movies</p>
				<ul class="list-unstyled">
				{% for movie in upcoming.results %}
					<a href="{% url 'detail' id=movie.id %}"><li>{{movie.title}}</li></a>
				{% endfor %}
				</ul>

				<p class="h3-responsive text-center bg-dark text-white">Popular Movies</p>
				<ul class="list-unstyled">
				{% for movie in popular.results %}
					<a href="{% url 'detail' id=movie.id %}"><li>{{movie.title}}</li></a>
				{% endfor %}
				</ul>

				<p class="h3-responsive text-center bg-dark text-white">Top Rated Movies</p>
				<ul class="list-unstyled">
				{% for movie in top_rated.results %}
					<a href="{% url 'detail' id=movie.id %}"><li>{{movie.title}}</li></a>
				{% endfor %}
				</ul>
		    </div>
		  </div>
		</div>

	{% endif %}

{% endblock %}

halls/templates/halls/movies.html
{% extends 'halls/base.html' %}
{% block content %}
{% for movie in movies %}
<div class="card">
  <img src="http://image.tmdb.org/t/p/original//{{ movie.poster_path }}" class="card-img-top" alt="{{ movie.title }}">
  <div class="card-body">
    <h5 class="card-title">{{ movie.title }}</h5>
    <p class="card-text">{{ movie.overview }}</p>
    <p class="card-text"><small class="text-muted"></small></p>
  </div>
</div>
{% endfor %}
{% endblock content %}

halls/templates/halls/update_list.html
{% extends 'halls/base.html' %}
{% block content %}
<div class="container">
<h2>Edit Your Fav vidz list</h2>
<form method="post">
  {% csrf_token %}
  {% load widget_tweaks %}
  {% for field in form %}
  <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
    {{ field.errors }}
    {{ field.label_tag }}
    {% render_field field class="form-control" %}
  </div>
  {% endfor %}
<button type="submit" class="btn btn-primary">Save</button>
</form>
<br>
<a href="{% url 'delete_list' hall.id %}" class="btn btn-danger">Delete this list</a>
</div>
{% endblock %}